services:
  - docker

before_install:
  - docker build -t flantastic_docker .
  - docker run -d -p 127.0.0.1:80:4567 flantastic_docker
  - docker ps -a

script:
  - docker run flantastic_docker /bin/sh -c "/root/.poetry/bin/poetry run python manage.py test flantastic/"
  