langage: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker build -t flantastic_docker .
  - docker ps -a

script:
  - docker run flantastic_docker /bin/sh -c "/root/.poetry/bin/poetry run python ./quicktest.py flantastic --db={sqlite}"
  