# Generated by Django 2.2.6 on 2019-10-06 20:44

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enseigne', models.CharField(max_length=256)),
                ('codpos', models.CharField(blank=True, max_length=8)),
                ('commune', models.CharField(blank=True, max_length=256)),
                ('siren', models.BigIntegerField(null=True)),
                ('vmaj', models.CharField(default=None, max_length=256, null=True)),
                ('vmaj1', models.CharField(default=None, max_length=256, null=True)),
                ('vmaj2', models.CharField(default=None, max_length=256, null=True)),
                ('vmaj3', models.CharField(default=None, max_length=256, null=True)),
                ('datemaj', models.CharField(default=None, max_length=256, null=True)),
                ('pate', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texture', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gout', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('apparence', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.CharField(blank=True, max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
