# Generated by Django 2.2.6 on 2019-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeries',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
