# Generated by Django 2.2.5 on 2019-12-04 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerie',
            name='global_note',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
