# Generated by Django 2.2.6 on 2019-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0002_bakeries_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeries',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
