# Generated by Django 2.2.6 on 2019-10-20 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flantastic', '0003_auto_20191007_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeries',
            name='gout',
        ),
        migrations.CreateModel(
            name='Taste_choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('bakerie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flantastic.Bakeries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
