# Generated by Django 2.2.6 on 2019-10-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0004_auto_20191020_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste_choice',
            name='bakerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flantastic.Bakeries'),
        ),
    ]
