# Generated by Django 2.2.6 on 2019-10-27 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0005_auto_20191020_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taste_choice',
            old_name='rate',
            new_name='gout',
        ),
        migrations.RemoveField(
            model_name='bakeries',
            name='apparence',
        ),
        migrations.RemoveField(
            model_name='bakeries',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='bakeries',
            name='pate',
        ),
        migrations.RemoveField(
            model_name='bakeries',
            name='texture',
        ),
        migrations.AddField(
            model_name='taste_choice',
            name='apparence',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='taste_choice',
            name='commentaire',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='taste_choice',
            name='pate',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='taste_choice',
            name='texture',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
