# Generated by Django 2.2.6 on 2019-10-27 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flantastic', '0006_auto_20191027_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bakeries',
            new_name='Bakerie',
        ),
        migrations.RenameModel(
            old_name='Taste_choice',
            new_name='Vote',
        ),
    ]
