# Generated by Django 2.2.6 on 2019-11-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0007_auto_20191027_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL),
        ),
    ]
