# Generated by Django 2.2.6 on 2019-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0008_auto_20191101_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
