# Generated by Django 2.2.6 on 2019-11-03 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flantastic', '0009_vote_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerie',
            name='global_note',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
